### PR TITLE
Add video support, continued ( #24 )

### PR DESCRIPTION
**Pull request by cabalex**
I haven't seen anyone working on video support since #24 , I thought I'd give it a shot. This PR might be a bit rough around the edges, but hopefully it's able to be added given some polish.

- [x] Animation control now affects the video (including stepping)
- [x] IE11 support
- [x] onLoad readded (mostly, see below)
- [x] FlagGroupBar/FlagGroupPanel kept as "Select image"
- [x] References to "Image" changed to "Element"
- [x] Other minor changes requested in the original PR

**The major remaining issue is IE support.**

* buildRectangularFlagFromElement.js - I've been working on IE support for a while, but I just can't seem to get it to work. VideoTexture isn't supported by IE, and the only workaround I could find was [drawing the video to a canvas and using the canvas as the texture](https://github.com/mrdoob/three.js/issues/7560). However, I can't seem to get IE to draw the video to the canvas. It'll draw images fine, but refuses to draw videos. [This demo](https://gist.github.com/cabalex/4a133e720d2663014fe624b38fe64d29) mostly replicates how the canvas is drawn in this workaround, as seen below. I'm not sure if this is an issue shared by others (I couldn't find anything else about it online) or if it just doesn't work in this specific case. Any help would be appreciated in that regard, if you know anything about it. If everything else is compatible, videos should be as well!
   * If we can't find a solution, it would be better to remove the workaround and its corresponding code in Flag.js to just leave it as a black flag. Maybe a warning toast or something?

image

Other minor notes:
* Flag.js/AnimationModule.js - For some reason every reference to the `<video>` element turns into a dict that contains null texture data `{ data: [255, 255, 255], width: 1, height: 1 }`. `this.imageElement` and `this.isVideo` are both defined properly on construction and reset/play (video tag, true), but is set to the above Object when the video is playing. I assume this is just a side effect of passing the video element into Three.js's VideoTexture, but I got around this by adding the video to the DOM and grabbing it with `document.getElementById` every time. The only place that this doesn't work is with IE support when loading one video after another, as it grabs the wrong video element.
* BuildAsyncFlagFromElement.js - URL input is checked here- I found it was easiest to check it just by a simple string suffix match. File input, however, is checked with `options.type`. It might be better to enforce consistency across both input methods, but this way doesn't involve checking/setting the media type in multiple places (on both input dialogues, from URL parameters, etc). I'm also unsure if you would have wanted to just string match or do something else. The original PR didn't support loading videos from a URL.
* FileInput.js - Why are onChange and onLoad both needed again? I feel like the original author removed onLoad because it loaded the video twice. I've commented out this onLoad argument so that it doesn't do that, but I'm not sure if you needed it for something.

Let me know what you think!

### CODE REVIEW

**Comment by krikienoid** [comment]
Hey there, thanks for all your work on this. I took a look and wrote down some feedback, though I don't think I quite understand how everything is supposed to work yet so nothing is set in stone.

1. I wouldn't worry too much about IE support, it's just a nice to have. Especially if it means adding messy workarounds. I'd be fine with just defaulting to the white flag and displaying an error message. Something like "Browser feature not supported." I just want to make sure errors are actually being caught and handled so none of these new features causes IE to completely crash, since everything else in FlagWaver is otherwise supported. Also fun fact but the canvas textures were actually implemented before for other reasons before I got rid of it, I might end up bringing it back to address an unrelated an issue.

2. I would like the video element to be referenced directly instead of calling documentById. On the off chance that I get around to adding multiple flags, I don't want to be relying on a global ID like that. This is also causing some weird issues I noticed when I tested.
    - Found a bug where multiple video elements are added each time the input is changed. Looks like this happens if you enter a web URL that doesn't resolve.

Screen Shot 2021-11-01 at 8 28 35 PM


3. I believe I was using [File.type](https://developer.mozilla.org/en-US/docs/Web/API/File/type) to check for valid file types, I thought it would be easier than managing a list of file extensions, but I agree it should be consistent.
    - Maybe there should be separate buildAsyncFlagFromImage and buildAsyncFlagFromVideo functions, then in app/components/FlagGroup.js the type check runs and chooses the correct function. FlagGroup.js can access options.file.type so we wouldn't need to manually pass type property in every setOptions call.

4. There was a reason for separate onChange/onLoad, though I don't remember exactly what it was. I had to fiddle around with those pesky file inputs quite a bit to get it to work right. Something to do with the file loading being asynchronous and needing to wait for the file to finish loading. I think some parts of the app checks if the url is an empty string to determine if it's a web file input or not.

Nitpicky stuff
- Add a line break before/after if statements if there is other code above/below it.
- Also do this with const/let declarations
- Wondering if it makes sense to rename buildAsyncFlagFromElement to buildAsyncFlagFromHTMLElement
- Minor bug: Stop button should reset the video. It seems like it's already doing this, just need to trigger a re-render.
- flagwaver/subjects/Flag.js: Instead of having two separate properties this.element and this.isVideo, can this be one property this.textureVideo and have it be null for non-videos.

**Comment by cabalex** [comment]
Thanks for the quick reply on my PR! I've made some changes:

1. Removed WIP IE support. You're right that it's probably too much of a hassle right now. Plus, I don't think there's anywhere the app can crash using IE (it's just a rendering problem with OpenGL). A warning toast with "Browser feature not supported." now displays.
2. Whoops! It turns out I (or the original PR, I guess) didn't realize `options.texture` was something that the Flag had access to on construction. This is always the `<video>` element (whereas `this.mesh.material.map.image` is not), which fixes our issue completely.
   - AnimationModule.js has also changed to reflect this. Expanding to multiple flags in the future shouldn't be as difficult now. `getFlag()` probably doesn't need to be called on every `play() / pause() / step() / reset()`, but it's flagGroupModule doesn't exist on construction or `init()`, and needs to change as the flag changes.
3. Split buildAsyncFlagFromElement into buildAsyncFlagFromImage and buildAsyncFlagFromVideo and they are now both called from FlagGroup using a cleaner matching function.
4. I didn't modify this since I'm still unsure of its use and it doesn't seem to do anything but cause problems when it's enabled.

- Improved formatting (line breaks!)
- The stop button resets the `<video>`'s position, but I can't seem to trigger a rerender (it's not `app.render()` or something like `app.update(0)`?).

**Comment by krikienoid** [comment]
Hi, thanks again for your work on this. I'll take a deeper look later tonight but for now I just took a quick look.

## src/assets/js/app/components/FlagGroup.js

For isVideo, are you able to check using `type.match('video.*')`? I believe `options.file.type` should be available to access here.

What is window.document.documentMode? Is that a browser sniffing test for IE? I would prefer to detect whatever error or missing feature in IE is causing the issue. If that's not possible, let's make it more explicit that this is checking for IE.

Also make sure to always fall back to the default white flag for any kind of error.

This is roughly what I'm thinking.

    buildAsyncFlagFromVideo(src, options)
        .then((flag) => {
            if (supportsVideoTexture) {
            // if (!isBrowserIE11) {
                this.updateFlag(flag);
            } else {
                addToast({ ... })

                buildAsyncFlagFromImage(DEFAULT_FLAG_IMAGE_PATH, options)
                    .then((flag) => {
                        this.updateFlag(flag);
                    });
            }
        });

## src/assets/js/flagwaver/app/modules/AnimationModule.js

Can the play/pause/step methods be handled entirely in Flag.js? If not, I still want to make sure that this still works regardless of if there is one or multiple flags. I think there should be something we can use for that...

## src/assets/js/flagwaver/helpers/buildAsyncFlagFromVideo.js 

The function name here should match the filename buildAsyncFlagFromVideo.js

Also can the supportsVideoTexture/isBrowserIE11 checks I mentioned earlier be handled by the promise in this function? This would be more consistent with how the other errors are handled.

## src/assets/js/flagwaver/helpers/buildRectangularFlagFromElement.js 

Let's rename this to buildRectangularFlagFromMedia

## src/assets/js/flagwaver/subjects/Flag.js 

I think THREE.VideoTexture inherits from THREE.Texture so it's not necessary to specify both in {THREE.Texture||THREE.VideoTexture}

Also can you un-nest that first double nested if statement.

## misc

Lastly, try wrapping the video re-render call inside as setTimeout(() => {}, 0). It could be that the HTML video element view doesn't refresh immediately so the render call needs to be deferred

**Comment by cabalex** [comment]
Addressed most of the above issues:

- FlagGroup.js - The reason I check for both file extension and file type is that `options.type` isn't set for URL input (I mention this in BuildAsyncFlagFromElement.js in the original PR message). `options.file` isn't accessible here, since only `src` and `type` are set from FlagGroupBar and FlagGroupPanel.
   - `window.document.documentMode` is an IE sniffing check, which I've made more clear. I don't think it's possible to check if the texture isn't rendering, since it doesn't throw any errors. I do check this twice in this commit, which may not be ideal (see below).
- AnimationModule.js - I don't think these can be handled entirely in Flag.js itself, since the UI only calls play/pause/step in AnimationModule. I've modified this to get all flags from every FlagGroupModules and play/pause/step each one, in case you have multiple flag modules. It would be ideal if all video playback code could be handled in Flag.js, but I don't know if that's completely possible without messier code.
- buildAsyncFlagFromVideo.js - You mention that you want the check to be handled inside the Promise- I'm not sure if you'd rather have just one IE check in FlagGroup.js and a generic "Video could not be loaded" message for everything, a specific error message passed in the reject call, or something else. It should be consistent between buildAsyncFlagFromVideo and buildAsyncFlagFromImage, but I don't know about having two IE checks. I could be overthinking it though.
   - Also oops, forgot to change the function name haha
- buildRectangularFlagFromElement.js renamed to buildRectangularFlagFromMedia.js
- Flag.js - Fixed.
- I still can't get it to work, even with a setTimeout... I'm also unsure how I would trigger a rerender from inside Flag.js, since I don't think it has access to App (I've been trying under AnimationModule's reset() function, calling a reset and setting a timeout for a rerender).

**Comment by krikienoid** [comment]
I just took a closer look and here is the rest of my feedback. I think it's mostly minor stuff at this point, this is looking pretty close.

app/components/FileInput.js
- I think the type property can be removed in these function calls.
- Do you know why window.URL.createObjectURL was added and the reader load event removed? It looks like this is the reason onLoad/onChange was changed in the other components. I would prefer not having to change all of this unless there is a good reason to.

app/components/FlagGroupBar.js and FlagGroupPanel.js
- Passing type property here should no longer be necessary
- I don't think the changes to handleFilePickerChange would've been necessary if FileInput.js hadn't been changed.

flagwaver/helpers/buildRectangularFlagFromImage and buildRectangularFlagFromVideo
- `import buildRectangularFlagFromElement...` should fit onto one line now that it's not more than 80 char long

flagwaver/helpers/buildRectangularFlagFromElement
- Add line break at L19

flageaver/helpers/loadVideo.js
- Move `video.src - src;` below the other properties

flagwaver/subjects/Flag.js
- Is it necessary/is there a benefit to checking this.videoElement.paused before calling paused() and play() ?

**Comment by krikienoid** [comment]
I see you just posted a another update, thanks! I'll take another look

**Comment by krikienoid** [comment]
I see the what you mean about checking the type in FlagGroup.js. I've found a solution to that, just pass fileRecord to FlagGroup. Probably a good idea to make fileRecord a member of Flag.options, but that's a problem for another day.

app/components/FlagGroup.js:

    renderModule() {
        const { fileRecord, options, addToast } = this.props;
        const src = options.src || DEFAULT_FLAG_IMAGE_PATH;

        const { file } = fileRecord;
        const isVideo = file && file.type.match('video.*');

        console.log('fileRecord',fileRecord)
        console.log('isVideo',!!isVideo)

app/containers/FlagGroupContainer.js:

    const mapStateToProps = state => ({
        fileRecord: state.fileRecord,
        options: state.flagGroup
    });

As for the promise error catch, I didn't realize this meant the same function had to handle both types of errors, but this can be solved by having the promise return multiple values.

src/assets/js/flagwaver/helpers/buildAsyncFlagFromVideo.js:

        if (isBrowserIE11) {
            reject({
                flag: buildFlag(options),
                msg: 'Browser feature not supported.'
            });
        }

        loadVideo(
            src,
            (element) => {
                resolve(
                    buildRectangularFlagFromMedia(element, options)
                );
            },
            () => {
                reject({
                    flag: buildFlag(options),
                    msg: 'Video could not be loaded.'
                });
            }
        );

app/components/FlagGroup.js:

            .catch(({ flag, msg }) => {
                    this.updateFlag(flag);

                    addToast({
                        status: 'error',
                        message: msg
                    });
                });

**Comment by cabalex** [comment]
This commit should address all of these.

Some comments:

- FlagGroup.js - We still need the extension check in `isVideo` for internet video, since it doesn't have a file or file type. I put `mp4|mov` there as some common formats, but I'm not sure if you wanted to add any more or check the URL in a different way (HEAD request for Content-Type?)
   - `DEFAULT_FLAG_IMAGE_PATH` isn't the white flag returned by a rejected Promise from buildAsyncFlagFromVIdeo/Image, but I suppose it's okay
- Flag.js - The video needs to check if it's paused for the simulate() function, which calls play() every time. It also prevents some console errors from showing if the video is played while it is already playing, or vice versa.
   - I just realized some if statements are redundant, so I've modified those to just call the play/pause functions

**Comment by krikienoid** [comment]
I've made a few edits and addressed some issues. I think this is close to the finish line, but I still want to take some time to review and test before merging.

- Still need to do browser testing.
- Does the Step button automatically loop when the end of the video is reached? (need to test).
- Large videos cause the computer to lag horribly, but I don't think there's much that can be done about that.
- Adding a mute button to AnimationControlBar would be a nice to have.

**Comment by krikienoid** [comment]
I've started to do some browser testing, and unfortunately found a major bug in Safari (14.1.2) where the entire page will crash when the end of a video is reached.

**Comment by cabalex** [comment]
Awesome work! Unfortunately I don't have access to Safari so I can't do any testing on that front, but it looks like you're handling things well.

You mentioned that large videos cause a lot of lag- wouldn't it be easier on performance to just get the file with [`URL.createObjectURL`](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) instead of [`FileReader.readAsDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL)? I'm fairly sure `readAsDataURL` [reads the whole file into memory as a base64 encoded string](https://stackoverflow.com/questions/31742072/filereader-vs-window-url-createobjecturl), which is a lot more taxing than generating a URL from the file itself. You might need to revoke the URL later during deconstruction, but it would probably lag less. I'm not sure if there was a problem with this solution other than code cleanliness, but it might be better performance-wise.

**Comment by krikienoid** [comment]
I was testing using the web URL input when I noticed the lag. Since the web URL input doesn't go through the FileReader, I don't think changing that will help. For reference, [this was the video I used for testing](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4).

If you do end up finding a solution to the lag, I think it would be worth looking into as a separate PR.

For now, I consider the main priority to be ensuring cross browser support. I'm okay with making an exception for IE, but not if multiple browsers are having trouble. The Safari bug is the only major bug I'm currently aware of, but I also haven't done a lot of testing yet.

**Comment by cabalex** [comment]
Just curious, any updates over the past few months? I feel like this branch is pretty stable.

I was able to get access to a Mac with Safari (14.1.2) through a friend, but I couldn't seem to reproduce the crashing error you were experiencing with Safari... [the video](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4) seemed to play back fine and repeat perfectly at the end without issue. Were you using a local file? (perhaps it crashed trying to reload the whole video, which is a different issue?)

I've tested other browsers and they seem to work perfectly (Chrome 101.0.4951.67, Edge 101.0.1210.53, Firefox 101.0), along with the mobile devices I own (iPad 15.4.1: Safari, Chrome 102.0.5005.67, Android 12: Chrome 101.0.4951.61)
Unfortunately I don't have any older versions of these browsers/OSes to test, but it seems to work relatively flawlessly for me.

**Comment by krikienoid** [comment]
Hi there,

- I tested on Safari 15.1 for MacOS 12.0.1
- I used this [video](https://www.youtube.com/watch?v=zGDzdps75ns) after first downloading it to my computer as an .mp4

I looked at it again today and am still seeing the same freezing issue, BUT I noticed that if I let my computer idle for several minutes, the animation will eventually start up again and keep going. Which is still unbelievably bad for an 8 second video, but it's not completely stopping like I had originally believed. Let me know if you are seeing the same.

Safari in general just seems to have some pretty terrible performance. From what I can gather, [newer versions of Safari have some kind of issue that is affecting all WebGL apps](https://discourse.threejs.org/t/horrible-3d-three-js-performance-in-latest-safari-on-macos/25940/18). So I'm thinking that it may not be an actual issue with the code or the video, though I'm not quite sure how to handle this type of issue. What really needs to happen is for Apple/Webkit to fix their broken browser :/

I'll take your word that it works fine in the other browsers, it looks like you got a decent variety of browsers/devices in your tests, so thank you for that. We can mark that complete at least.

**Comment by krikienoid** [comment]
Update: Some good news and bad news.

I think I found a band-aid for the Safari problem. Not a real solution, just something to make the app at least barely usable until Webkit fixes their WebGL problems.

It's quite simple. FlagWaver already caps the number of max updates per frame to 90. I can just set this to a smaller number like, 2. Now Safari can maintain a stable rate at a speedy 7 FPS 😂😂😂 ...a significant improvement over 0 FPS!

Bad news is I did some more browser testing and found another bug. In Opera, the step forward button doesn't work properly.

**Comment by krikienoid** [comment]
I believe this PR is in good shape and have merged it to the dev branch. There are a few things I wish to take care of before I deploy it however.

**Comment by krikienoid** [comment]
This feature is now live as of v2.1.0.

**Pull request merged**
